#!/usr/bin/env bash

check_factor()
{
    num=$1
    for ((i=2; i*i<=num; i++)); do
        while ((num % i == 0)); do
            factors+=($i)
            num=$((num / i))
        done
    done
    if ((num > 1)); then
        factors+=($num)
    fi

    if [ ${#factors[@]} -ge 2 ]; then
        num1=${factors[0]}
        num2=${factors[1]}
        echo "$1=$num1*$num2"
    fi
}

if [ $# -ne 1 ]
then
    echo 'Usage: factors <file>'
    exit 1
else
    while read i
    do
        factors=()
        check_factor "$i"
    done < "$1"
fi
